server:
  port: 9527

spring:
  application:
    name: springcloud-zuul-geteway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7002:7002/eureka/,http://eureka7001:7001/eureka/,http://eureka7003:7003/eureka/
  instance:
    instance-id: This is Zuul-9527
    prefer-ip-address: true

info:
  app.name: mildlamb-springcloud-zuul
  company.name: gnardada.com

# Zuul配置
zuul:
  routes:
    mylocation.serviceId: springcloud-provider-location
    mylocation.path: /mylocation/**
  # 不允许通过服务名去访问服务，只能用上面自定义的路径去访问
  ignored-services: springcloud-provider-location